export const LOAD_DATA = 'LOAD_DATA'
export const DRAW_LOAD_DATA = 'DRAW_LOAD_DATA'
export const SUCCESS_LOAD_DATA = 'SUCCESS_LOAD_DATA'
export const FAILED_LOAD_DATA = 'FAILED_LOAD_DATA'

export const ADD_DATA = 'ADD_DATA'
export const DRAW_ADD_DATA = 'DRAW_ADD_DATA'
export const SUCCESS_ADD_DATA = 'SUCCESS_ADD_DATA'
export const FAILED_ADD_DATA = 'FAILED_ADD_DATA'

export const REMOVE_DATA = 'REMOVE_DATA'
export const DRAW_REMOVE_DATA = 'DRAW_REMOVE_DATA'
export const SUCCESS_REMOVE_DATA = 'SUCCESS_REMOVE_DATA'
export const FAILED_REMOVE_DATA = 'FAILED_REMOVE_DATA'